
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Real-Time-Translator

on:
  push:
    branches:
      - dev
    paths:
      - 'AI-agent-SpeechTranslator/**'
      - '.github/workflows/dev_real-time-translator.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet dependencies
        run: dotnet restore AI-agent-SpeechTranslator/AI-agent-SpeechTranslator.csproj

      - name: Build with dotnet
        run: dotnet build AI-agent-SpeechTranslator/AI-agent-SpeechTranslator.csproj --configuration Release --no-restore

      - name: Create .env file
        run: |
          New-Item -Path "AI-agent-SpeechTranslator/.env" -ItemType "file" -Force
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "SPEECH_API_KEY=${{ secrets.SPEECH_API_KEY }}"
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "SPEECH_ENDPOINT=${{ secrets.SPEECH_ENDPOINT }}"
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "SPEECH_REGION=${{ secrets.SPEECH_REGION }}"
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "TRANSLATOR_API_KEY=${{ secrets.TRANSLATOR_API_KEY }}"
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "TRANSLATOR_ENDPOINT=${{ secrets.TRANSLATOR_ENDPOINT }}"
          Add-Content -Path "AI-agent-SpeechTranslator/.env" -Value "TRANSLATOR_REGION=${{ secrets.TRANSLATOR_REGION }}"

      - name: dotnet publish
        run: dotnet publish AI-agent-SpeechTranslator/AI-agent-SpeechTranslator.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Real-Time-Translator'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C3B682182DA34E9D874A279EFDF0115B }}